[versions]
kotlin = "2.3.20-Beta2"
androidGradlePlugin = "9.1.0-alpha07"
gradle-develocityPlugin = "4.3.1"
gradle-toolchainsResolverPlugin = "1.0.0"
appVersioning = "1.5.0"
paparazzi = "2.0.0-alpha04"
burst = "2.12.0-beta1"
licensee = "1.14.1"
apollo = "5.0.0-alpha.4"
apollo-adapters = "0.7.0"
apollo-mockserver = "0.3.1"
googleServices = "4.4.4"
invert = "0.0.9"
detekt = "2.0.0-alpha.2"
androidPublisher = "4.0.0"
skie = "0.10.9"
kotlinpoet = "2.2.0"
leakcanary = "2.14"
metro = "0.10.3"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
firebase-analytics = "23.0.0"
firebase-appDistributionPlugin = "5.2.1"
firebase-remoteConfig = "23.0.1"
firebase-perf = "22.0.4"
firebase-perfPlugin = "2.0.2"
firebase-crashlytics = "20.0.4"
firebase-crashlyticsPlugin = "3.0.6"
androidx-lint = "1.0.0-alpha05"
androidx-compose-ui = "1.11.0-alpha04"
androidx-compose-foundation = "1.11.0-alpha04"
androidx-compose-runtime = "1.11.0-alpha04"
androidx-compose-tracing = "1.11.0-alpha04"
androidx-compose-material3 = "1.5.0-alpha13"
androidx-core = "1.18.0-alpha01"
androidx-coreSplashscreen = "1.2.0"
androidx-activity = "1.13.0-alpha01"
androidx-lifecycle = "2.10.0"
androidx-navigation3 = "1.1.0-alpha03"
androidx-datastore = "1.3.0-alpha05"
androidx-work = "2.11.1"
androidx-browser = "1.10.0-alpha02"
androidx-media3 = "1.9.1"
androidx-profileinstaller = "1.4.1"
androidx-benchmark = "1.5.0-alpha02"
androidx-tracing = "1.3.0"
androidx-tracing-perfetto = "1.0.0"
androidx-test-runner = "1.7.0"
androidx-test-rules = "1.7.0"
androidx-test-ext-junit = "1.3.0"
androidx-test-uiautomator = "2.4.0-alpha07"
molecule = "2.2.0"
okhttp = "5.1.0"
okio = "3.16.4"
coil = "3.3.0"
sqldelight = "2.2.1"
ksoup = "0.2.5"
turbine = "1.2.1"
kermit = "2.0.8"
crashKios = "0.8.5"
testkit = "0.17"

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-powerAssert = { module = "org.jetbrains.kotlin:kotlin-power-assert", version.ref = "kotlin" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
plugin-appVersioning = { module = "io.github.reactivecircus.appversioning:app-versioning-gradle-plugin", version.ref = "appVersioning" }
plugin-paparazzi = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }
plugin-burst = { module = "app.cash.burst:burst-gradle-plugin", version.ref = "burst" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
plugin-metro = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
plugin-apollo = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
plugin-invert = { module = "com.squareup.invert:com.squareup.invert.gradle.plugin", version.ref = "invert" }
plugin-googleServices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
plugin-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlyticsPlugin" }
plugin-firebasePerf = { module = "com.google.firebase:perf-plugin", version.ref = "firebase-perfPlugin" }
plugin-appDistribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebase-appDistributionPlugin" }
plugin-detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-detektKtlintWrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
plugin-skie = { module = "co.touchlab.skie:co.touchlab.skie.gradle.plugin", version.ref = "skie" }
plugin-sqldelight = { module = "app.cash.sqldelight:app.cash.sqldelight.gradle.plugin", version.ref = "sqldelight" }
plugin-baselineprofile = { module = "androidx.baselineprofile:androidx.baselineprofile.gradle.plugin", version.ref = "androidx-benchmark" }
androidPublisher = { module = "com.github.triplet.gradle:android-publisher", version.ref = "androidPublisher" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-plumber = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakcanary" }
metrox-viewmodelCompose = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-remoteConfig = { module = "com.google.firebase:firebase-config", version.ref = "firebase-remoteConfig" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebase-perf" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
androidx-lintGradle = { group = "androidx.lint", name = "lint-gradle", version.ref = "androidx-lint" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-runtimeAnnotation = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "androidx-compose-tracing" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-coreSplashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-coreSplashscreen" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-benchmark-macroJunit = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-tracing = { module = "androidx.tracing:tracing-ktx", version.ref = "androidx-tracing" }
androidx-tracing-perfetto = { module = "androidx.tracing:tracing-perfetto", version.ref = "androidx-tracing-perfetto" }
androidx-tracing-perfetto-binary = { module = "androidx.tracing:tracing-perfetto-binary", version.ref = "androidx-tracing-perfetto" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "okhttp" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-normalizedCache = { module = "com.apollographql.apollo:apollo-normalized-cache", version.ref = "apollo" }
apollo-adapters-core = { module = "com.apollographql.adapters:apollo-adapters-core", version.ref = "apollo-adapters" }
apollo-mockserver = { module = "com.apollographql.mockserver:apollo-mockserver", version.ref = "apollo-mockserver" }
sqldelight-coroutinesExtensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-androidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-nativeDriver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-sqliteDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
licentia-runtime = { module = "io.github.reactivecircus.licentia:licentia-runtime" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
burst = { module = "app.cash.burst:burst", version.ref = "burst" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
crashKios = { module = "co.touchlab:crashkios", version.ref = "crashKios" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
testkit = { id = "com.autonomousapps.testkit", version.ref = "testkit" }
